

# Site settings

title: Design Portfolio
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Freelance web designer and developer, specialising in Jekyll, HTML, CSS and JavaScript
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: johnmelville
github_username:  johnmelville
google_username: johnmelville

permalink: /:categories/:title

links:
    - title: about
      url: /about
    - title: work
      url: /work
    - title: articles
      url: /articles
    - title: hire me
      url: /hire-me

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
